name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Set up dependencies
      run: |
        pip install coverage
        pip install -r requirements.txt

    - name: Unit test
      run: |
        python3 -m unittest discover -s tests

    - name: Coverage test
      run: |
        python3 -m coverage run -m unittest discover tests
        python3 -m coverage report
        python3 -m coverage xml
